"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    let admin = await queryInterface.bulkInsert(
      "inventory",
      [
        {
          "iInventoryId": "845",
          "vBillNo": "SI/PWSNR/11148",
          "iAssetType": "8",
          "vAssetName": "Samsung",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "RZ8M811YKZB",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Samsung A30-Blue",
          "vRate": "",
          "dtPurchaseDate": "2019-09-02 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2019-09-01 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "Dual core",
          "vOS": "Andorid 9",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "04:BA:8D:19:47:02",
          "vComment": "IMEI NUMBER=358084106972534, SAPL-MOB-055"
        },
        {
          "iInventoryId": "846",
          "vBillNo": "SI/PWSNR/11149",
          "iAssetType": "8",
          "vAssetName": "Samsung",
          "vAssetUser": null,
          "vRam": "6GB",
          "vSerialNumber": "RZ8M72ELAGW",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Samsung Galaxy M40-Midnight Blue",
          "vRate": "",
          "dtPurchaseDate": "2019-09-02 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2019-09-02 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "Octa-Core",
          "vOS": "Android 10",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "3C:20:F6:9A:13:CE",
          "vComment": "IMEI NO:- 357346101915623, SAPL-MOB-056"
        },
        {
          "iInventoryId": "847",
          "vBillNo": "FABVQT2000051052",
          "iAssetType": "8",
          "vAssetName": "Realme",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "Y5U8RKGUWGTKUSF",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Realme 3I",
          "vRate": "",
          "dtPurchaseDate": "2019-10-22 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2020-10-21 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "Octa Core",
          "vOS": "Andorid 9",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "58:85:e9:b5:73:5f",
          "vComment": "IMEI No:-869775043530317, SAPL-MOB-057"
        },
        {
          "iInventoryId": "848",
          "vBillNo": "FAC95X2000319249",
          "iAssetType": "8",
          "vAssetName": "ViVO",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Vivo VY17",
          "vRate": "",
          "dtPurchaseDate": "2019-10-22 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2020-10-21 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "Octa Core",
          "vOS": "Andorid 9",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "18:02:AE:6E:C5:BF",
          "vComment": "IMEI NUMBER:- 860657045568967, SAPL-MOB-058"
        },
        {
          "iInventoryId": "849",
          "vBillNo": "FAA2D12000006903",
          "iAssetType": "8",
          "vAssetName": "MI",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "F7C63755353E",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "MI A3(Gery 64GB)",
          "vRate": "",
          "dtPurchaseDate": "2019-10-22 00:00:00",
          "vWarrentyPeriod": "1 Year",
          "dtExpiryDate": "2020-10-21 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "Octa Core",
          "vOS": "Andorid 9",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "04:C8:07:0C:CC:CB",
          "vComment": "IMEI NUMBER:- 863540048810692,863540048810700, SAPL-MOB-059"
        },
        {
          "iInventoryId": "850",
          "vBillNo": "FAAAJU2000066050",
          "iAssetType": "8",
          "vAssetName": "Nokia 8.1",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "PNXID19100901808",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Nokia 8.1 (Iron,64 GB)",
          "vRate": "",
          "dtPurchaseDate": "2019-10-22 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2020-10-21 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "Octa Core",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "94:EE:9F:03:C0:0F",
          "vComment": "IMEI NUMBER:- 356964092309456,356964092479457, SAPL-MOB-060"
        },
        {
          "iInventoryId": "851",
          "vBillNo": "UIPLA 192001896",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPC3H08N735",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "iPhone 11 64 GB(Black)",
          "vRate": "",
          "dtPurchaseDate": "2020-02-19 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2021-02-19 00:00:00",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "88:A9:B7:6F:88:CD",
          "vComment": "IME/MEID 356573109104931, SAPL-MOB-061"
        },
        {
          "iInventoryId": "852",
          "vBillNo": "DEL5-4960864",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "B0719KYGMQ",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPhone 8",
          "vRate": "",
          "dtPurchaseDate": "2020-02-24 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2021-02-23 00:00:00",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "3C:CD:36:3F:F2:B2",
          "vComment": "SAPL-MOB-062"
        },
        {
          "iInventoryId": "853",
          "vBillNo": "UIPLA202101397",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPDG0DK0F0Q",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Iphone 12",
          "vRate": "",
          "dtPurchaseDate": "2020-12-07 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2021-12-06 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "F8:10:93:98:D5:C6",
          "vComment": "IMEI NO:-353058111562733 / IMEI NO:-353058111443876, SAPL-MOB-063"
        },
        {
          "iInventoryId": "854",
          "vBillNo": "UIPLA202101445",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "C7CDJFF80GPP",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Iphone 12 Mini",
          "vRate": "",
          "dtPurchaseDate": "2020-12-11 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2021-12-10 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "FC:66:CF:DD:90:84",
          "vComment": "IMEI NO:- 353017112766362 / IMEI NO2:- 353017112048357, SAPL-MOB-064"
        },
        {
          "iInventoryId": "855",
          "vBillNo": "UIPLA202101445",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DX4DJ4H2N735",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Iphone 11 Black",
          "vRate": "",
          "dtPurchaseDate": "2020-12-11 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2021-12-10 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "BC:A5:A9:84:5E:BC",
          "vComment": "IMEI NO:- 351941232257469 / IMEI NO2:- 351941232363382, SAPL-MOB-065"
        },
        {
          "iInventoryId": "856",
          "vBillNo": "UIPLA212200182",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "GV4DQ24QKXK1",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Iphone XR",
          "vRate": "",
          "dtPurchaseDate": "2021-05-12 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-11 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI NO:- 352884112566899, SAPL-MOB-066"
        },
        {
          "iInventoryId": "857",
          "vBillNo": "UIPLA212200185",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "F2LF61QQ0D4Y",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Iphone 12 Pro MAX",
          "vRate": "",
          "dtPurchaseDate": "2021-05-13 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-12 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI NO:-352850799881224, SAPL-MOB-067"
        },
        {
          "iInventoryId": "858",
          "vBillNo": "UIPLA212200185",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPFG1T30D8X",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Iphone 12 Pro",
          "vRate": "",
          "dtPurchaseDate": "2021-05-13 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-12 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI NO:-357171855764195, SAPL-MOB-068"
        },
        {
          "iInventoryId": "859",
          "vBillNo": "AMD2-374495",
          "iAssetType": "8",
          "vAssetName": "Oppo",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "B089MV4H2W",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Oppo A31",
          "vRate": "",
          "dtPurchaseDate": "2021-05-13 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-12 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI NO:-864717043645930 / IMEI NO:-864717043645922, SAPL-MOB-069"
        },
        {
          "iInventoryId": "860",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Redmi",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "31144/81RH03796",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Redmi Note 10 Shadow Black",
          "vRate": "",
          "dtPurchaseDate": "2021-05-13 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-12 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "Andorid 9",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI NO:- 866769059122856 / IMEI NO:- 866769059122864, SAPL-MOB-070"
        },
        {
          "iInventoryId": "861",
          "vBillNo": "AMD2-449901",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "C6KDQNQT0GPP",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPhone 12 Mini (64GB) - Black",
          "vRate": "",
          "dtPurchaseDate": "2021-05-19 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-18 00:00:00",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI NO:-353023116952610, SAPL-MOB-071"
        },
        {
          "iInventoryId": "862",
          "vBillNo": "SJAB-534",
          "iAssetType": "8",
          "vAssetName": "Samsung",
          "vAssetUser": null,
          "vRam": "6GB",
          "vSerialNumber": "B0915TFJHN",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Samsung Galaxy F62 (Laser Grey)",
          "vRate": "",
          "dtPurchaseDate": "2021-05-20 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-05-19 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "SAPL-MOB-072"
        },
        {
          "iInventoryId": "863",
          "vBillNo": "T-103",
          "iAssetType": "8",
          "vAssetName": "Jio Phone",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "RNOMPAIA0036580",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Jio Phone Next",
          "vRate": "",
          "dtPurchaseDate": "2022-06-28 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2023-06-27 00:00:00",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "Android 12",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "IMEI:- 357559828087860 / IMEI:- 357559828887863 / SIM NO:- +916352616104 / PROVIDE TO HR TEAM (SHUCHI) / SAPL-MOB-073"
        },
        {
          "iInventoryId": "864",
          "vBillNo": "T-103",
          "iAssetType": "8",
          "vAssetName": "Jio Phone",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "RNOMPLHA0033802",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Jio Phone Next",
          "vRate": "",
          "dtPurchaseDate": "2022-06-28 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2023-06-27 00:00:00",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "Android 12",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "9C:85:66:1E:7B:E9",
          "vComment": "IMEI:- 355628149029299 / IMEI:- 357559820908014, SAPL-MOB-074"
        },
        {
          "iInventoryId": "865",
          "vBillNo": "T-142",
          "iAssetType": "8",
          "vAssetName": "Jio Phone",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Jio Phone Next",
          "vRate": "",
          "dtPurchaseDate": "2022-07-20 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-07-06 00:00:00",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "Android 12",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "SAPL-MOB-075"
        },
        {
          "iInventoryId": "866",
          "vBillNo": "T-162",
          "iAssetType": "8",
          "vAssetName": "Jio Phone",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Jio Phone Next",
          "vRate": "",
          "dtPurchaseDate": "2022-08-04 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2022-08-03 00:00:00",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "Android 12",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "",
          "vComment": "SAPL-MOB-076"
        },
        {
          "iInventoryId": "867",
          "vBillNo": "FAMA-137863",
          "iAssetType": "8",
          "vAssetName": "Redmi",
          "vAssetUser": null,
          "vRam": "4GB",
          "vSerialNumber": "43553/S2YJ03468",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Redmi Pad",
          "vRate": "",
          "dtPurchaseDate": "2023-02-03 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2024-02-02 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "",
          "vOS": "Android 12",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "E0:80:6B:F8:85:12",
          "vComment": "SAPL-MOB-077"
        },
        {
          "iInventoryId": "868",
          "vBillNo": "IN-2725",
          "iAssetType": "8",
          "vAssetName": "Google",
          "vAssetUser": null,
          "vRam": "6GB",
          "vSerialNumber": "26161JEGR11360",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Google Pixcel 6a",
          "vRate": "",
          "dtPurchaseDate": "2023-02-03 00:00:00",
          "vWarrentyPeriod": "1 year",
          "dtExpiryDate": "2024-02-02 00:00:00",
          "vMotherBoard": "",
          "vStorage": "128GB",
          "vProcessor": "",
          "vOS": "Android 12",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "24:29:34:90:99:0D",
          "vComment": "SAPL-MOB-078"
        },
        {
          "iInventoryId": "869",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Samsung",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "RF1C59WZ5M",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Samsungs Galaxy Tab 2 (Black)",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "18:3F:47:81:CE:2E",
          "vComment": "SA-MOB-006"
        },
        {
          "iInventoryId": "870",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Motorola",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Motorola Nexus 6 (Midnight Blue)",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "A4:70:D6:BE:E7:C5",
          "vComment": "SA-MOB-010"
        },
        {
          "iInventoryId": "871",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Asus",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "ECAZFG275958",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Asus Zenphone - Black",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "F0:79:59:A7:68:00",
          "vComment": "SA-MOB-018"
        },
        {
          "iInventoryId": "872",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Spice",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "MI498HA14090118",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Spice Android One-Black",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "BC:D1:D3:FD:55:8C",
          "vComment": "SA-MOB-021"
        },
        {
          "iInventoryId": "873",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "LG",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "072961E0DE51419",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "LG Nexus 5-Black",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "34:4D:F7:47:B4:73",
          "vComment": "SA-MOB-031"
        },
        {
          "iInventoryId": "874",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Samsung",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Samsung J7 Prime",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "5C:99:60:C3:71:37",
          "vComment": "SA-MOB-033"
        },
        {
          "iInventoryId": "875",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Google",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Google Pixel",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "ac:37:43:52:36:5d",
          "vComment": "SA-MOB-034"
        },
        {
          "iInventoryId": "876",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Lenovo",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "HNB3NQ0A",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "LENOVO K8 PLUS",
          "vRate": "",
          "dtPurchaseDate": "2018-03-12 00:00:00",
          "vWarrentyPeriod": "1 Year",
          "dtExpiryDate": "2019-03-11 00:00:00",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "F4:1B:A1:C1:A1:EE",
          "vComment": "SA-MOB-041"
        },
        {
          "iInventoryId": "877",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "HUAWEI",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "86S7N18531001104",
                    "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "HUAWEI",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "A4:93:3f:22:36:2B",
          "vComment": "SA-MOB-050"
        },
        {
          "iInventoryId": "878",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "HTC",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "HQ85Y1H00197",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "HTC DESIRE 12+",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "40:4E:36:E5:2D:9B",
          "vComment": "SA-MOB-051"
        },
        {
          "iInventoryId": "879",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "LG",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "808IPTA0007713",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "LG Q7",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "00:57:C1:B5:38:9C",
          "vComment": "SA-MOB-052"
        },
        {
          "iInventoryId": "880",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Huawei",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "867924038578970",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Huawei-Y3",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "DC:72:9B:07:4C:74",
          "vComment": "SA-MOB-053"
        },
        {
          "iInventoryId": "881",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Samsung",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "RZ8G702ZPZR",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Samsung Galaxy S6 - Blue",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "C0:BD:D1:F4:9D:C2",
          "vComment": "ST-MOB-002"
        },
        {
          "iInventoryId": "882",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Dell",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "CNQ0V22",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Dell Venue 8 Tablet-16GB-Black",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "40:E2:30:9B:54:13",
          "vComment": "SA-MOB-012"
        },
        {
          "iInventoryId": "883",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "F18SXCPRHG7F",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPhone 7-32GB-Black",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "40:4D:7F:85:5C:7E",
          "vComment": "SA-MOB-003"
        },
        {
          "iInventoryId": "884",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "FK2P2P7RG5QR",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPhone 6 Plus-16GB-White",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "24:24:0E:D2:BB:43",
          "vComment": "SA-MOB-007"
        },
        {
          "iInventoryId": "885",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "FNMV664EG5MP",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple Iphone 6 Silver 16 GB",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "50:82:d5:91:99:BD",
          "vComment": "SA-MOB-008"
        },
        {
          "iInventoryId": "886",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "F2LNQ6WNG5QQ",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPhone 6 Plus-16GB-Space Gray",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "54:9F:13:14:E3:8B",
          "vComment": "SA-MOB-009"
        },
        {
          "iInventoryId": "887",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "C8QP7RBKG5MQ",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPhone 6-16GB-Gold",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "28:5A:EB:E1:94:42",
          "vComment": "SA-MOB-019"
        },
        {
          "iInventoryId": "888",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DLXMPPUMFCM8",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPad mini 2-16GB-Silver",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "16GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "C8:F6:50:53:F4:36",
          "vComment": "SA-MOB-020"
        },
        {
          "iInventoryId": "889",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPNFN4YG5MC",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple Iphone 6 Gray",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "70:3E:AC:5D:43:D9",
          "vComment": "SA-MOB-035"
        },
        {
          "iInventoryId": "890",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "F2NVQ6Y6JCLF",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple Iphone X Black 64 GB",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "54:33:CB:94:A7:41",
          "vComment": "SA-MOB-036"
        },
        {
          "iInventoryId": "891",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "GCGW10ZZHLF9",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple iPad WIFI",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "32GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "B0:CA:68:E3:E2:EF",
          "vComment": "SA-MOB-045"
        },
        {
          "iInventoryId": "892",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPVXFCYJCLG",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple Iphone X 64 GB - Silver",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "B8:C1:11:83:CC:21",
          "vComment": "SA-MOB-046"
        },
        {
          "iInventoryId": "893",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPVK9AMJCLF",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple Iphone X 64 GB - BLACK",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "64GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "B0:19:C6:70:83:6C",
          "vComment": "SA-MOB-047"
        },
        {
          "iInventoryId": "894",
          "vBillNo": "NA",
          "iAssetType": "8",
          "vAssetName": "Apple",
          "vAssetUser": null,
          "vRam": "",
          "vSerialNumber": "DNPVPBVYJCL8",
          "bIsTrash": "0",
          "bIsRepair": "0",
          "vBrandMaker": "Apple Iphone X-Black",
          "vRate": "",
          "vWarrentyPeriod": "0 Year",
          "vMotherBoard": "",
          "vStorage": "256GB",
          "vProcessor": "",
          "vOS": "",
          "dtCreatedAt": "2023-08-18 00:00:00",
          "dtUpdatedAt": "2023-08-18 00:00:00",
          "tiDeletedAt": "0",
          "vLanMacAddress": "",
          "vWifiMacAddress": "3C:2E:FF:13:B2:D5",
          "vComment": "SA-MOB-048"
        }
      ],
      {},
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("inventory", null, {});
  },

};